// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smwhfsufszkrklnnacld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtd2hmc3Vmc3prcmtsbm5hY2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTkyOTUsImV4cCI6MjA1NTQ3NTI5NX0.6Qsfk3PGWAe41qvnNIgqOQacK3qUcKwVE7rK84NV1lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);